# Colors (Zenburn)
# Orginally designed by jnurmine for vim.

# Default colors
[colors.primary]
background = '#3A3A3A'
foreground = '#DCDCCC'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#E89393'
green   = '#688060'
yellow  = '#F0DFAF'
blue    = '#93B3A3'
magenta = '#BCA3A3'
cyan    = '#93B3A3'
white   = '#CCCCCC'

# Bright colors
[colors.bright]
black   = '#222222'
red     = '#DCA3A3'
green   = '#7F9F7F'
yellow  = '#EFEF8F'
blue    = '#8CD0D3'
magenta = '#C0BED1'
cyan    = '#8CD0D3'
white   = '#FFFFFF'

[font]
normal = { family = "Source Code Pro", style = "Regular" }
size = 7